name: 'Awesome Prepare Environment'
description: 'Setup node, dependencies and caching'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 12.18.4
    - uses: actions/cache@v2
      id: cache-awesome-dependencies
      with:
        key: cache-awesome-dependencies-${{ hashFiles(./package-lock.json) }}
        path: ./node_modules
    - if: steps.cache-awesome-dependencies.outputs.cache-hit != 'true'
      run: npm install
