name: Awesome Linter

on: pull_request

jobs:
  lint-js:
    name: Lint JS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/awesome-prepare-environment@v1
    - run: npm run test-js

  lint-css:
    name: Lint CSS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/awesome-prepare-environment@v1
    - run: npm run test-css
